### ISSUE TITLE
Login with Metamask & google not working

### ISSUE THREAD

**Issue by sarora180673** [rairprotocol/rair-official-library#22]
main branch

Observation :  Stuck at Connecting. I think the issue is with rairSDK.auth.createUser

![Screenshot from 2024-11-14 01-35-22-1](https://github.com/user-attachments/assets/fe8a1d97-a6c8-481a-9188-925802303aa7)

**Comment by SeanM322** [comment]
@sarora180673 
https://github.com/rairprotocol/rair-official-library/pull/23

**Comment by SeanM322** [comment]
Already merged 
we can close it @RAIReth
